version: '3'

services:
  # Example project
  myproject:
    build: .
    volumes:
      - ./myproject/mydjango/urls.py:/app/mydjango/urls.py:cached
      - ./myproject/mydjango/settings_override.py:/app/mydjango/settings_override.py:cached
      - ./myproject/myapp:/app/myapp:cached
    # depends_on:
    #   - db
    ports:
      - '8000:8000'
# Database - Uncomment and change settings_override.py to use
#   db:
#     image: mariadb:10.3
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: mydjango
#     volumes:
#       - db_data:/var/lib/mysql
#     ports:
#       - 8086:3306

# volumes:
#   db_data:
